# ç½‘ç«™çš„åŸºæœ¬ä¿¡æ¯
site:
  tab: Frosti # æµè§ˆå™¨æ ‡ç­¾æ ä¸Šæ˜¾ç¤ºçš„æ–‡æœ¬
  title: ğŸ’  Frosti # ç½‘ç«™çš„æ ‡é¢˜
  description: A clean, elegant, and fast static blog template! ğŸš€ Developed with Astro # ç½‘ç«™çš„æè¿°ï¼Œç”¨äºSEOç­‰
  language: en # ç½‘ç«™çš„è¯­è¨€ï¼Œä¾‹å¦‚ "en" æ˜¯è‹±æ–‡
  favicon: /favicon.ico # ç½‘ç«™çš„å›¾æ ‡ï¼Œç”¨äºæµè§ˆå™¨æ ‡ç­¾æ å’Œå…¶ä»–åœ°æ–¹æ˜¾ç¤º
  theme: # æ›´å¤šä¸»é¢˜ https://daisyui.com/docs/themes/
    light: winter # ä¸»é¢˜çš„æµ…è‰²æ¨¡å¼
    dark: dracula # ä¸»é¢˜çš„æ·±è‰²æ¨¡å¼
    code: github-dark # ä»£ç å—çš„ä¸»é¢˜ https://shiki.style/themes
  date_format: ddd MMM DD YYYY # æ—¥æœŸæ ¼å¼è®¾ç½®ï¼Œæ”¯æŒè‡ªå®šä¹‰æ ¼å¼
  menu: # èœå•é…ç½®
    - id: home # èœå•é¡¹çš„å”¯ä¸€æ ‡è¯†ç¬¦
      text: Home # èœå•é¡¹æ˜¾ç¤ºçš„æ–‡æœ¬
      href: / # èœå•é¡¹é“¾æ¥çš„åœ°å€
      svg: "material-symbols:home-outline-rounded"
      target: _self

monster:
  logo: /image
  drink:
    original: /image/drink/original
    reserve: /image/drink/reserve
    ultra: /image/drink/ultra
    juice: /image/drink/juice
    rehab: /image/drink/rehab
    java: /image/drink/java
    triple_shot: /image/drink/triple_shot

# ç”¨æˆ·çš„ä¸ªäººä¿¡æ¯
user:
  name: EveSunMaple # ç”¨æˆ·å
  site: "https://frosti.saroprock.com" # ç”¨æˆ·çš„ç½‘ç«™é“¾æ¥
  avatar: /profile.png # ç”¨æˆ·å¤´åƒè·¯å¾„
  sidebar: # ä¾§è¾¹æ é…ç½®
    social:
      - href: "https://afdian.com/a/saroprock" # é“¾æ¥
        ariaLabel: Support my work # å›¾æ ‡çš„å¯è®¿é—®æ€§æ ‡ç­¾
        title: Support my work # å›¾æ ‡çš„æ‚¬æµ®æ ‡é¢˜
        svg: "ri:cup-line"
      - href: "https://github.com/EveSunMaple"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/438392347"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/EveSunMaple"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
  footer:
    social:
      - href: "https://afdian.com/a/saroprock" # é“¾æ¥
        ariaLabel: Support my work # å›¾æ ‡çš„å¯è®¿é—®æ€§æ ‡ç­¾
        title: Support my work # å›¾æ ‡çš„æ‚¬æµ®æ ‡é¢˜
        svg: "ri:cup-line"
      - href: "https://github.com/EveSunMaple"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/438392347"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/EveSunMaple"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
